// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrZo_dTxw_pSyOfsCi_Axpx2rG_pwVU4g',
    appId: '1:352421908255:web:cfc05279150d7cfd2caa2a',
    messagingSenderId: '352421908255',
    projectId: 'study-ai-assistant',
    authDomain: 'study-ai-assistant.firebaseapp.com',
    storageBucket: 'study-ai-assistant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpL2TB-SmPpBXsZNUdN9gjoYM4K_IYS2I',
    appId: '1:352421908255:android:3b86e044b7a4dbf32caa2a',
    messagingSenderId: '352421908255',
    projectId: 'study-ai-assistant',
    storageBucket: 'study-ai-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxfLBB_2DBdi7wgFMA0S4L0xxHDEg7z9c',
    appId: '1:352421908255:ios:34073adfba1c08592caa2a',
    messagingSenderId: '352421908255',
    projectId: 'study-ai-assistant',
    storageBucket: 'study-ai-assistant.firebasestorage.app',
    iosBundleId: 'com.example.studyAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxfLBB_2DBdi7wgFMA0S4L0xxHDEg7z9c',
    appId: '1:352421908255:ios:34073adfba1c08592caa2a',
    messagingSenderId: '352421908255',
    projectId: 'study-ai-assistant',
    storageBucket: 'study-ai-assistant.firebasestorage.app',
    iosBundleId: 'com.example.studyAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrZo_dTxw_pSyOfsCi_Axpx2rG_pwVU4g',
    appId: '1:352421908255:web:fd0b0b716cd663062caa2a',
    messagingSenderId: '352421908255',
    projectId: 'study-ai-assistant',
    authDomain: 'study-ai-assistant.firebaseapp.com',
    storageBucket: 'study-ai-assistant.firebasestorage.app',
  );

}