name: Flutter CI

on:
  push:
    branches: [ main ]
    paths:
      - 'flutter_app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'flutter_app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_app

    - name: Analyze project
      run: flutter analyze
      working-directory: ./flutter_app

    - name: Run tests
      run: flutter test
      working-directory: ./flutter_app
